export const data = [
    {
        id: 1,
        LVName: "LV-001",
        Capacity: 1000,
        MasterRegNum: "M789",
        MastersName: "John Doe",
        MastersContactNumber: "1234567890",
        MastersNIDImageAttachment: "nid_image.jpg",
        StaffName: "Jane Smith",
        StaffNIDNo: "S987654",
        Leased: 1,
        CompanyName: "ABC Corporation",
        ProprietorsName: "Alice Johnson",
        OfficeAddress: "123 Main Street",
        AccountNumber: "9876543210",
        PhoneNumber: "01712345678",
        LVDocumentsAttachment: "documents.pdf",
        Status: 1,
    },
    // Add more objects here
    {
        id: 2,
        LVName: "LV-002",
        Capacity: 800,
        MasterRegNum: "M123",
        MastersName: "Jane Smith",
        MastersContactNumber: "9876543210",
        MastersNIDImageAttachment: "nid_image2.jpg",
        StaffName: "John Doe",
        StaffNIDNo: "S654321",
        Leased: 0,
        CompanyName: "XYZ Corporation",
        ProprietorsName: "Bob Johnson",
        OfficeAddress: "456 Elm Street",
        AccountNumber: "1234567890",
        PhoneNumber: "01876543210",
        LVDocumentsAttachment: "documents2.pdf",
        Status: 0,
    },
    // // Add more objects here
    // {
    //     id: 3,
    //     LVName: "LV-003",
    //     Capacity: 1200,
    //     MasterRegNum: "M456",
    //     MastersName: "Sarah Wilson",
    //     MastersContactNumber: "0123456789",
    //     MastersNIDImageAttachment: "nid_image3.jpg",
    //     StaffName: "Michael Brown",
    //     StaffNIDNo: "S234567",
    //     Leased: 1,
    //     CompanyName: "PQR Industries",
    //     ProprietorsName: "Emma Davis",
    //     OfficeAddress: "789 Oak Street",
    //     AccountNumber: "6789054321",
    //     PhoneNumber: "01987654321",
    //     LVDocumentsAttachment: "documents3.pdf",
    //     Status: 1,
    // },
    // // Add more objects here
    // {
    //     id: 4,
    //     LVName: "LV-004",
    //     Capacity: 1500,
    //     MasterRegNum: "M234",
    //     MastersName: "Emily Wilson",
    //     MastersContactNumber: "0192837465",
    //     MastersNIDImageAttachment: "nid_image4.jpg",
    //     StaffName: "Robert Smith",
    //     StaffNIDNo: "S345678",
    //     Leased: 0,
    //     CompanyName: "LMN Enterprises",
    //     ProprietorsName: "David Miller",
    //     OfficeAddress: "789 Elm Street",
    //     AccountNumber: "5678901234",
    //     PhoneNumber: "01654789321",
    //     LVDocumentsAttachment: "documents4.pdf",
    //     Status: 1,
    // },
    // {
    //     id: 5,
    //     LVName: "LV-005",
    //     Capacity: 2000,
    //     MasterRegNum: "M567",
    //     MastersName: "Jessica Brown",
    //     MastersContactNumber: "0184756291",
    //     MastersNIDImageAttachment: "nid_image5.jpg",
    //     StaffName: "Andrew Johnson",
    //     StaffNIDNo: "S456789",
    //     Leased: 1,
    //     CompanyName: "RST Corporation",
    //     ProprietorsName: "Olivia Davis",
    //     OfficeAddress: "456 Oak Street",
    //     AccountNumber: "3456789012",
    //     PhoneNumber: "01738592016",
    //     LVDocumentsAttachment: "documents5.pdf",
    //     Status: 0,
    // },
    // {
    //     id: 6,
    //     LVName: "LV-006",
    //     Capacity: 1800,
    //     MasterRegNum: "M890",
    //     MastersName: "Sophia Miller",
    //     MastersContactNumber: "0176283947",
    //     MastersNIDImageAttachment: "nid_image6.jpg",
    //     StaffName: "Jacob Wilson",
    //     StaffNIDNo: "S567890",
    //     Leased: 1,
    //     CompanyName: "EFG Corporation",
    //     ProprietorsName: "Daniel Anderson",
    //     OfficeAddress: "987 Maple Street",
    //     AccountNumber: "9012345678",
    //     PhoneNumber: "01574628390",
    //     LVDocumentsAttachment: "documents6.pdf",
    //     Status: 1,
    // },
    // {
    //     id: 7,
    //     LVName: "LV-007",
    //     Capacity: 1100,
    //     MasterRegNum: "M345",
    //     MastersName: "Sophie Johnson",
    //     MastersContactNumber: "0165839204",
    //     MastersNIDImageAttachment: "nid_image7.jpg",
    //     StaffName: "Matthew Davis",
    //     StaffNIDNo: "S678901",
    //     Leased: 0,
    //     CompanyName: "HIJ Enterprises",
    //     ProprietorsName: "Emma Wilson",
    //     OfficeAddress: "789 Pine Street",
    //     AccountNumber: "2345678901",
    //     PhoneNumber: "01485972634",
    //     LVDocumentsAttachment: "documents7.pdf",
    //     Status: 1,
    // },
];
